// Re-export Lucide icons for consistent usage
import {
  Music,
  Play,
  Pause,
  SkipBack,
  SkipForward,
  Shuffle,
  Repeat,
  Volume2,
  VolumeX,
  Heart,
  HeartOff,
  Download,
  Share2,
  Copy,
  Search,
  X,
  ChevronLeft,
  ChevronRight,
  ChevronDown,
  ChevronUp,
  Menu,
  Sun,
  Moon,
  Monitor,
  Settings,
  Plus,
  Trash2,
  Trash,
  Edit,
  ExternalLink,
  Clock,
  Calendar,
  User,
  Users,
  Globe,
  Shield,
  Bell,
  Key,
  Palette,
  Folder,
  FileText,
  Upload,
  ArrowLeft,
  ArrowRight,
  ArrowUpRight,
  Home,
  Compass,
  Sparkles,
  Crown,
  ListMusic,
  Mic,
  Expand,
  Minimize,
  Loader2,
  AlertCircle,
  CheckCircle,
  Check,
  Info,
  Eye,
  EyeOff,
  Lock,
  Mail,
  Zap,
  Dices,
  Flag,
  Camera,
  Image,
  Video,
  Headphones,
  Mic2,
  Cpu,
  Database,
  Server,
  Cloud,
  Wifi,
  Bluetooth,
  Usb,
  Tablet,
  Smartphone,
  Laptop,
  Printer,
  Phone,
  MessageCircle,
  MessageSquare,
  Send,
  Inbox,
  Archive,
  Star,
  Bookmark,
  Tag,
  Filter,
  SortAsc,
  SortDesc,
  Grid,
  List,
  Columns,
  Rows,
  Maximize,
  RotateCcw,
  RotateCw,
  FlipHorizontal,
  FlipVertical,
  Crop,
  ZoomIn,
  ZoomOut,
  Move,
  CornerUpLeft,
  CornerUpRight,
  CornerDownLeft,
  CornerDownRight,
} from "lucide-react";

export {
  Music,
  Play,
  Pause,
  SkipBack,
  SkipForward,
  Shuffle,
  Repeat,
  Volume2,
  VolumeX,
  Heart,
  HeartOff,
  Download,
  Share2,
  Copy,
  Search,
  X,
  X as Close,
  ChevronLeft,
  ChevronRight,
  ChevronDown,
  ChevronUp,
  Menu,
  Sun,
  Moon,
  Monitor,
  Settings,
  Plus,
  Trash2,
  Trash,
  Edit,
  ExternalLink,
  Clock,
  Calendar,
  User,
  Users,
  Globe,
  Shield,
  Bell,
  Key,
  Palette,
  Folder,
  FileText,
  Upload,
  ArrowLeft,
  ArrowRight,
  ArrowUpRight,
  Home,
  Compass,
  Sparkles,
  Crown,
  ListMusic,
  Mic,
  Expand,
  Minimize,
  Loader2,
  AlertCircle,
  CheckCircle,
  Check,
  Info,
  Eye,
  EyeOff,
  Lock,
  Mail,
  Zap,
  Dices as Dice,
  Flag,
  Camera,
  Image,
  Video,
  Headphones,
  Mic2,
  Cpu,
  Database,
  Server,
  Cloud,
  Wifi,
  Bluetooth,
  Usb,
  Tablet,
  Smartphone,
  Laptop,
  Printer,
  Phone,
  MessageCircle,
  MessageSquare,
  Send,
  Inbox,
  Archive,
  Star,
  Bookmark,
  Tag,
  Filter,
  SortAsc,
  SortDesc,
  Grid,
  List,
  Columns,
  Rows,
  Maximize,
  RotateCcw,
  RotateCw,
  FlipHorizontal,
  FlipVertical,
  Crop,
  ZoomIn,
  ZoomOut,
  Move,
  CornerUpLeft,
  CornerUpRight,
  CornerDownLeft,
  CornerDownRight,
};

// Custom Amber icons
export const AmberLogo = () => (
  <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
    <circle cx="12" cy="12" r="10"/>
    <path d="M8 14s1.5 2 4 2 4-2 4-2"/>
    <line x1="9" y1="9" x2="9.01" y2="9"/>
    <line x1="15" y1="9" x2="15.01" y2="9"/>
  </svg>
);

export const AmberLogoSmall = () => (
  <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
    <circle cx="12" cy="12" r="10"/>
    <path d="M8 14s1.5 2 4 2 4-2 4-2"/>
  </svg>
);

// Re-export commonly used icons with consistent names
export {
  Music as MusicIcon,
  Play as PlayIcon,
  Pause as PauseIcon,
  SkipBack as SkipBackIcon,
  SkipForward as SkipForwardIcon,
  Shuffle as ShuffleIcon,
  Repeat as RepeatIcon,
  Volume2 as Volume2Icon,
  VolumeX as VolumeXIcon,
  Heart as HeartIcon,
  HeartOff as HeartOffIcon,
  Download as DownloadIcon,
  Share2 as ShareIcon,
  Copy as CopyIcon,
  Search as SearchIcon,
  X as CloseIcon,
  ChevronLeft as ChevronLeftIcon,
  ChevronRight as ChevronRightIcon,
  ChevronDown as ChevronDownIcon,
  ChevronUp as ChevronUpIcon,
  Menu as MenuIcon,
  Sun as SunIcon,
  Moon as MoonIcon,
  Monitor as MonitorIcon,
  Settings as SettingsIcon,
  Plus as PlusIcon,
  Trash2 as TrashIcon,
  Edit as EditIcon,
  ExternalLink as ExternalLinkIcon,
  Clock as ClockIcon,
  Calendar as CalendarIcon,
  User as UserIcon,
  Users as UsersIcon,
  Globe as GlobeIcon,
  Shield as ShieldIcon,
  Bell as BellIcon,
  Key as KeyIcon,
  Palette as PaletteIcon,
  Folder as FolderIcon,
  FileText as FileTextIcon,
  Upload as UploadIcon,
  ArrowLeft as ArrowLeftIcon,
  ArrowRight as ArrowRightIcon,
  ArrowUpRight as ArrowUpRightIcon,
  Home as HomeIcon,
  Compass as CompassIcon,
  Sparkles as SparklesIcon,
  Crown as CrownIcon,
  ListMusic as ListMusicIcon,
  Mic as MicIcon,
  Expand as ExpandIcon,
  Minimize as MinimizeIcon,
  Loader2 as LoaderIcon,
  AlertCircle as AlertCircleIcon,
  CheckCircle as CheckCircleIcon,
  Check as CheckIcon,
  Info as InfoIcon,
  Eye as EyeIcon,
  EyeOff as EyeOffIcon,
  Lock as LockIcon,
  Mail as MailIcon,
  Zap as ZapIcon,
  Dices as DiceIcon,
  Flag as FlagIcon,
  Camera as CameraIcon,
  Image as ImageIcon,
  Video as VideoIcon,
  Headphones as HeadphonesIcon,
  Mic2 as Mic2Icon,
  Cpu as CpuIcon,
  Database as DatabaseIcon,
  Server as ServerIcon,
  Cloud as CloudIcon,
  Wifi as WifiIcon,
  Bluetooth as BluetoothIcon,
  Usb as UsbIcon,
  Tablet as TabletIcon,
  Smartphone as SmartphoneIcon,
  Laptop as LaptopIcon,
  Printer as PrinterIcon,
  Phone as PhoneIcon,
  MessageCircle as MessageCircleIcon,
  MessageSquare as MessageSquareIcon,
  Send as SendIcon,
  Inbox as InboxIcon,
  Archive as ArchiveIcon,
  Star as StarIcon,
  Bookmark as BookmarkIcon,
  Tag as TagIcon,
  Filter as FilterIcon,
  SortAsc as SortAscIcon,
  SortDesc as SortDescIcon,
  Grid as GridIcon,
  List as ListIcon,
  Columns as ColumnsIcon,
  Rows as RowsIcon,
  Maximize as MaximizeIcon,
  RotateCcw as RotateCcwIcon,
  RotateCw as RotateCwIcon,
  FlipHorizontal as FlipHorizontalIcon,
  FlipVertical as FlipVerticalIcon,
  Crop as CropIcon,
  ZoomIn as ZoomInIcon,
  ZoomOut as ZoomOutIcon,
  Move as MoveIcon,
  CornerUpLeft as CornerUpLeftIcon,
  CornerUpRight as CornerUpRightIcon,
  CornerDownLeft as CornerDownLeftIcon,
  CornerDownRight as CornerDownRightIcon,
};